version: '3'
networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
services:
  api1:
    build: ./api1
    networks:
            frontend:
                ipv4_address: 172.20.0.4
    ports:
     - "8001:8001"
  api2:
    build: ./api2
    networks:
            frontend:
                ipv4_address: 172.20.0.5
    ports:
     - "8002:8002"
  nginx:
    build: ./nginx
    networks:
            frontend:
                ipv4_address: 172.20.0.2
    ports:
      - "80:80"
    depends_on:
      - api1
      - api2